apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: lo1fh6jjr-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/lo1fh6jjr-dotnet-basic-gitops